### ISSUE TITLE
Future requests

### ISSUE THREAD

**Issue by AjieDev** [TFAGaming/DiscordJS-V14-ModMail-Bot#10]
Sorry, can you make the commands with prefix? , my bot broken bcs I host 2 code in 1 bot and try to scramble to register the slash command.

**Comment by svenbledt** [comment]
I recommend u to upgrade your bot to a more up to date variant then and use a bot with slash commands. 

I can recommend [this template](https://github.com/TFAGaming/DiscordJS-V14-Bot-Template)

Prefix commands are outdated and if you let me know what your bot should be able to do ill maybe write a new one with those functions for you.

**Comment by TFAGaming** [comment]
The prefix commands are complex nowadays, and I would recommend you use slash commands because they're very popular on Discord. You can create your own custom prefix command handler. If you have tried to make it before I comment, try to re-download the new source and try again, just to avoid any future problems.
